spring.profiles.active=qa
appname=mpay-busidemo
aescrypt.facade.enabled=true
#email.facade.enabled=true
#lock.facade.enabled=true
#redis.facade.enabled=true
#mq.facade.enabled=true
#serial.facade.enabled=true
#sms.facade.enabled=true
