spring.profiles.active=qa
appname=demo
aescrypt.facade.enabled=true
#email.facade.enabled=true
#lock.facade.enabled=true
#redis.facade.enabled=true
#mq.facade.enabled=true
#serial.facade.enabled=true
#sms.facade.enabled=true
#dubbo.pointcut=execution(* com.lianlianpay.demo.service..*(..))
